/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HzButton: typeof import('@hzlzh/ui')['Button']
    HzCol: typeof import('@hzlzh/ui')['Col']
    HzDialog: typeof import('@hzlzh/ui')['Dialog']
    HzIcon: typeof import('@hzlzh/ui')['Icon']
    HzInput: typeof import('@hzlzh/ui')['Input']
    HzPopper: typeof import('@hzlzh/ui')['Popper']
    HzRow: typeof import('@hzlzh/ui')['Row']
    HzVirtualTable: typeof import('@hzlzh/ui')['VirtualTable']
  }
}
