/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HzButton: typeof import('hzlzh-ui')['Button']
    HzDialog: typeof import('hzlzh-ui')['Dialog']
    HzIcon: typeof import('hzlzh-ui')['Icon']
    HzInput: typeof import('hzlzh-ui')['Input']
    HzPopper: typeof import('hzlzh-ui')['Popper']
    HzVirtualTable: typeof import('hzlzh-ui')['VirtualTable']
  }
}
